# Generated by Django 5.1.2 on 2024-10-24 06:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmactivity', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmactivity',
            old_name='activity_date',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='farmactivity',
            old_name='activity_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='farmactivity',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
