# Generated by Django 5.1.2 on 2024-10-21 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('planting_date', models.DateField()),
                ('harvest_date', models.DateField()),
                ('status', models.CharField(max_length=100)),
            ],
        ),
    ]
