# Generated by Django 5.1.2 on 2024-10-24 06:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crop',
            name='status',
        ),
        migrations.AddField(
            model_name='crop',
            name='yield_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='crop',
            name='planting_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
