# Generated by Django 5.1.2 on 2024-11-25 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0002_remove_crop_status_crop_yield_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='season',
            field=models.CharField(default='winter', max_length=50),
        ),
    ]
