# Generated by Django 5.1.2 on 2024-11-25 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='records',
            old_name='health_status',
            new_name='status',
        ),
    ]
