# Generated by Django 5.1.2 on 2024-11-25 18:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_rename_health_status_records_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='records',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 11, 25, 18, 54, 4, 119641, tzinfo=datetime.timezone.utc)),
        ),
    ]
